name: Crux
options:
  bundleIdPrefix: com.crux
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"

packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  Crux:
    type: application
    platform: [iOS, macOS]
    sources:
      - path: Shared
      - path: Resources/Reader
        buildPhase: resources
      - path: iOS
        excludes:
          - "**/*"
        platform: iOS
      - path: macOS
        excludes:
          - "**/*"
        platform: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.crux.app
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: Crux
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "14.0"
        UILaunchScreen: {}
        CFBundleDocumentTypes:
          - CFBundleTypeName: EPUB Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Default
            LSItemContentTypes:
              - org.idpf.epub-container
        UTImportedTypeDeclarations:
          - UTTypeIdentifier: org.idpf.epub-container
            UTTypeDescription: EPUB Document
            UTTypeConformsTo:
              - public.data
              - public.composite-content
            UTTypeTagSpecification:
              public.filename-extension:
                - epub
              public.mime-type:
                - application/epub+zip
    entitlements:
      path: Resources/Crux.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
    dependencies:
      - package: MarkdownUI

  CruxTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: Crux_macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.crux.tests
        GENERATE_INFOPLIST_FILE: YES

  CruxUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: UITests
    dependencies:
      - target: Crux_macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.crux.uitests
        GENERATE_INFOPLIST_FILE: YES
